<?php

namespace ContainerW9WtAJD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMuscicControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.n_0ia6A.App\Controller\MuscicController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.n_0ia6A.App\\Controller\\MuscicController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'musicRepo' => ['privates', 'App\\Repository\\MusicRepository', 'getMusicRepositoryService', true],
        ], [
            'musicRepo' => 'App\\Repository\\MusicRepository',
        ]))->withContext('App\\Controller\\MuscicController::index()', $container);
    }
}
