<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXTiQYAw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXTiQYAw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXTiQYAw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXTiQYAw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXTiQYAw\App_KernelDevDebugContainer([
    'container.build_hash' => 'XTiQYAw',
    'container.build_id' => '439f640f',
    'container.build_time' => 1741268641,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXTiQYAw');
