<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTUPpKTJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTUPpKTJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTUPpKTJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTUPpKTJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTUPpKTJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'TUPpKTJ',
    'container.build_id' => 'a70660fa',
    'container.build_time' => 1742150505,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTUPpKTJ');
