<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKKqBVpY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKKqBVpY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKKqBVpY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKKqBVpY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKKqBVpY\App_KernelDevDebugContainer([
    'container.build_hash' => 'KKqBVpY',
    'container.build_id' => 'fde6a303',
    'container.build_time' => 1744754448,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKKqBVpY');
